services:
  db:
    image: mysql:9.0
    container_name: govtrace_db_container
    restart: always
    environment:
      MYSQL_DATABASE: govtrace_db
      MYSQL_ROOT_PASSWORD: En648213!
    ports:
      - "3307:3306"
    volumes:
      - govtrace_data:/var/lib/mysql
    networks:
      - govtrace-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - govtrace-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: govtrace_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - govtrace-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: govtrace_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Variáveis necessárias para evitar o erro de Roles
      KAFKA_ENABLE_KRAFT: "false"
    networks:
      - govtrace-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: govtrace_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - govtrace-network

networks:
  govtrace-network:
    driver: bridge

volumes:
  govtrace_data: